# These are supported funding model platforms

github: pirate
patreon: theSquashSH
custom: 
  - https://paypal.me/NicholasSweeting
  - `BTC: 1HuxXriPE2Bbnag3jJrqa3bkNHrs297dYH`
  - `ETH: 0x5D4c34D4a121Fe08d1dDB7969F07550f2dB9f471`
