github: pirate
patreon: theSquashSH
custom: ["https://paypal.me/NicholasSweeting", "https://www.blockchain.com/btc/payment_request?address=1HuxXriPE2Bbnag3jJrqa3bkNHrs297dYH&message=ArchiveBox+donation+to+@pirate+on+Github&amount_local=25&currency=USD&nosavecurrency=true", "https://www.blockchain.com/eth/address/0x5D4c34D4a121Fe08d1dDB7969F07550f2dB9f471"]
