# Usage:
#     docker-compose up -d
#     docker-compose run archivebox init
#     echo "https://example.com" | docker-compose run archivebox archivebox add
#     docker-compose run archivebox add --depth=1 https://example.com/some/feed.rss
#     docker-compose run archivebox config --set PUBLIC_INDEX=True
# Documentation:
#     https://github.com/pirate/ArchiveBox/wiki/Docker#docker-compose

version: '3.7'

services:
    archivebox:
        # build: .
        image: nikisweeting/archivebox:latest
        command: server 0.0.0.0:8000
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        environment:
            - USE_COLOR=True
            - SHOW_PROGRESS=False
            # - HTTP_PROXY=http://pywb:8080  COMING SOON!
        volumes:
            - ./data:/data

    # pywb:
    #     image: webrecorder/pywb:latest
    #     entrypoint: /bin/sh 'wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback --proxy;'
    #     environment:
    #         - INIT_COLLECTION=archivebox
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         ./data:/archivebox
    #         ./data/wayback:/webarchive

#    nginx:
#        image: nginx:alpine
#        ports:
#            - 443:443
#            - 80:80
#        volumes:
#            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./data:/var/www
