---
- import_playbook: install_package.yml
  vars:
    install_packages:
      ffmpeg: {packages: ['ffmpeg']}
    state: 'present'

- import_playbook: install_pip.yml
  vars:
    install_pip:
      ytdlp: {packages: ['yt-dlp']}
    state: 'present'

- import_playbook: load_binaries.yml
  vars:
    load_binaries:
      ffmpeg: {bin_name: 'ffmpeg', version_cmd: 'ffmpeg -version'}
      ytdlp: {bin_name: 'yt-dlp', version_cmd: 'yt-dlp --version'}


- name: "Install YT-DLP"
  hosts: localhost
  gather_facts: no
  vars:
    YTDLP_VERSION_MIN: '2024.8.6'
  tasks:
    - name: Make sure Python and Pip are installed
      assert:
        that:
          - BINARIES.python.version
          - BINARIES.pip.version
          - BINARIES.ffmpeg.version
          - BINARIES.ytdlp.version
        quiet: true

    - name: Check that installed YT-DLP matches expected version
      assert:
        that: BINARIES.ytdlp.version is version(YTDLP_VERSION_MIN, '>=')
        quiet: true

    - debug:
        msg: "{{ {'BINARIES': BINARIES, 'BINPROVIDERS': BINPROVIDERS} }}"
