#!/usr/bin/env ansible-playbook
---

- import_playbook: ../puppeteer/install_puppeteer.yml
  when: BINARIES.chrome is not defined

- name: "Install Singlefile"
  hosts: localhost
  gather_facts: no
  vars:
    SINGLEFILE_VERSION_EXACT: '1.1.54'
  tasks:
    - include_role:
        name: setup_lib_npm
      vars:
        MIN_NODE_VERSION: '20.0.0'
        MIN_NPM_VERSION: '10.0.0'

    - name: "Install npm packages: [single-file-cli]"
      community.general.npm:
        name: 'single-file-cli@1.1.54'
        state: "present"
        path: '{{BINPROVIDERS.npm.root_path}}'

    - name: Load single-file binary from installed NPM package
      include_role:
        name: load_binary
      vars:
        name: singlefile
        bin_name: 'single-file'
        version_cmd: 'single-file --version'
        PATH: '{{BINPROVIDERS.npm.PATH}}'

    - name: Check that installed Singlefile version matches expected version
      assert:
        that: SINGLEFILE_VERSION_EXACT is version(BINARIES.singlefile.version, '==')
        quiet: true

    - debug:
        msg: "{{ {'BINARIES': BINARIES, 'BINPROVIDERS': BINPROVIDERS} }}"
