name: 🐞 Bug report
description: Report a bug or error you encountered in ArchiveBox
title: "Bug: ..."
assignees:
  - pirate
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all the fields below to get help with your issue.  
        **Do not skip the `archivebox version` field** or your issue will be closed automatically.  
        If you would like faster help make sure to **include a screenshot!**  

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A description of what the issue is, what you expected to happen, and if relevant, the *URLs you were trying to archive* (if relevant).  
        *Please note:* it is normal to see errors occasionally for some extractors on some URLs (not every extractor will work on every page, that's why it offers many extractors).  
        Please only report archiving errors if you are seeing them *consistently across many URLs* or if they are entirely *preventing you from using ArchiveBox*.
      placeholder: |
        Got a bunch of 'singlefile was unable to archive this page' errors when trying to archive URLs from this site:
          https://example.com/xyz ...
        I also tried to archive the same URLs using `singlefile` directly and some of them worked but not all of them.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Please include the exact steps you took to trigger the issue.
      placeholder: |
        1. Started ArchiveBox by running: `docker run -v $PWD:/data -p 8000:8000 archivebox/archivebox:latest`
        2. Went to the https://127.0.0.1:8000/add/ page in Google Chrome
        3. Typed 'https://example.com/xyz' into the 'Add URL' input field
        4. Clicked the 'Add+' button
        5. Got a 500 error and saw this output in terminal: '...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or log output
      description: "Please **paste a screenshot of the issue** and/or any terminal output or logs (check `data/logs/errors.log` as well)."
      placeholder: 
      render: shell
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: ArchiveBox Version
      description: |
        Run the `archivebox version` command and paste the *full* output here (*not just the version number*).  
        If using Docker run:    `docker run archivebox/archivebox version`  
        For Docker Compose run: `docker compose run archivebox version`  
      render: shell
      placeholder: |
        0.8.6
        ArchiveBox v0.8.6rc0 COMMIT_HASH=721427a BUILD_TIME=2024-10-21 12:57:02 1729515422
        IN_DOCKER=False IN_QEMU=False ARCH=arm64 OS=Darwin PLATFORM=macOS-15.1-arm64-arm-64bit PYTHON=Cpython (venv)
        EUID=502:20 UID=502:20 PUID=502:20 FS_UID=502:20 FS_PERMS=644 FS_ATOMIC=True FS_REMOTE=False
        DEBUG=False IS_TTY=True SUDO=False ID=dfa11485:aa78ad45 SEARCH_BACKEND=ripgrep LDAP=False
        
        Binary Dependencies:
        √  python                3.11.9       venv_pip   ~/archivebox/.venv/bin/python
        √  django                5.1.2        venv_pip   ~/archivebox/.venv/lib/python3.11/site-packages/django/__init__.py
        √  sqlite                2.6.0        venv_pip   ~/archivebox/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py
        √  pip                   24.3.1       venv_pip   ~/archivebox/.venv/bin/pip
        ...
    validations:
      required: true

  - type: dropdown
    id: operating_system
    validations:
      required: true
    attributes:
      label: What host operating system/environment are you running ArchiveBox on?
      description: |
        *Please note we are unable to provide support for Windows users unless you are [running in Docker](https://github.com/ArchiveBox/archivebox#:~:text=windows%20without%20docker).*  
      multiple: false
      options:
        - Linux (Ubuntu/Debian/Arch/Alpine/etc.)
        - macOS (including Docker on macOS)
        - BSD (FreeBSD/OpenBSD/NetBSD/etc.)
        - Windows (including WSL, WSL2, Docker Desktop on Windows)

  - type: checkboxes
    id: filesystem
    attributes:
      label: What type of drive are you using to store your ArchiveBox data?
      description: Are you using a [remote filesystem](https://github.com/ArchiveBox/ArchiveBox/wiki/Setting-Up-Storage#supported-remote-filesystems) or FUSE mount for `data/` or `data/archive` (e.g. NFS/SMB/CIFS/etc. or FUSE/RClone/S3/B2/OneDrive/etc.)?
      options:
        - label: Data is on a local SSD or NVMe drive
          required: false
        - label: Data is on a spinning hard drive or USB drive
          required: false
        - label: Data is on a network mount (e.g. NFS/SMB/CIFS/etc.)
          required: false
        - label: Data is on a FUSE mount (e.g. SSHFS/RClone/S3/B2/OneDrive, etc.)
          required: false
  
  - type: dropdown
    id: install_method
    validations:
      required: true
    attributes:
      label: How did you install the version of ArchiveBox you are using?
      multiple: false
      options:
        - pip
        - apt
        - brew
        - nix
        - Docker (or other container system like podman/LXC/Kubernetes or TrueNAS/Cloudron/YunoHost/etc.)
        - Other

  - type: textarea
    id: docker_compose_yml
    attributes:
      label: Docker Compose file
      description: "If using Docker Compose, please share your full `docker-compose.yml` file (or the `docker run ...` command you use)."
      placeholder: |
        services:
            archivebox:
                image: archivebox/archivebox:latest
                ports:
                    - 8000:8000
                volumes:
                    - ./data:/data
                environment:
                    - ADMIN_USERNAME=admin
                    - ADMIN_PASSWORD=****<redact any passwords>****
                    - ALLOWED_HOSTS=*
                    - CSRF_TRUSTED_ORIGINS=https://archivebox.example.com
                    - PUBLIC_INDEX=True
                    - PUBLIC_SNAPSHOTS=True
                    - PUBLIC_ADD_VIEW=False
                    ...

            archivebox_scheduler:
                image: archivebox/archivebox:latest
                command: schedule --foreground --update --every=day
                environment:
                    ...
      
          ...
      render: shell
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: ArchiveBox Configuration
      description: "Please share your full `data/ArchiveBox.conf` file here."
      render: shell
      placeholder: |
        [SERVER_CONFIG]
        SECRET_KEY = "*********<redact any secrets/passwords>************"

        WGET_RESTRICT_FILE_NAMES=windows
        USE_SYSTEM_WGET=true
        CHECK_SSL_VALIDITY=false
        ...
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        <br/>
        <hr/>
        <br/>
        We strive to answer issues as quickly as possible, it usually takes us *about a ~week* to respond.  
        Make sure your archive `data/` is [**fully backed up**](https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#disk-layout) before trying anything suggested here, **we are not responsible for data loss**.  
        <br/>
        In the meantime please consider:  
          - [💰 Donating](https://github.com/ArchiveBox/ArchiveBox/wiki/Donations) to support ArchiveBox open-source
          - [👨‍✈️ Hiring us](https://docs.monadical.com/s/archivebox-consulting-services) for corporate deployments with professional support, custom feature development, help with CAPTCHAs/rate-limits.
          - [🔍 Searching the docs](https://docs.archivebox.io/) for answers to common questions
          - 📚 Reading the [Troubleshooting Guide](https://github.com/ArchiveBox/ArchiveBox/wiki)
          - ✨ Trying a newer [`BETA` release](https://github.com/ArchiveBox/ArchiveBox/releases) (issues are often already fixed in our latest `BETA` releases)
        
