---
- name: Make sure lib folders exist
  file:
    path: '{{item}}'
    state: directory
    recurse: true
  loop:
    - '{{LIB_DIR_PIP}}'
    - '{{LIB_DIR_BIN}}'
  when: BINPROVIDERS.pip is not defined

- name: Load Python and Pip binaries
  import_role:
    name: load_binary
  vars:
    name: '{{item}}'
  loop:
    - python
    - pip
  when: BINARIES.python is not defined or BINARIES.pip is not defined

- assert:
    that:
      - BINARIES.python.version is version(MIN_PYTHON_VERSION, '>=')
      - BINARIES.pip.version is version(MIN_PIP_VERSION, '>=')
    quiet: true
  when: BINPROVIDERS.pip is not defined

###################################################################################


# - name: "Install pip packages: {{install_pip}}"
#   ansible.builtin.pip:
#     name: '{{item}}'
#     state: "{{state}}"
#     virtualenv: '{{LIB_DIR_PIP}}/venv'
#     virtualenv_python: "{{BINARIES.python.abspath}}"
#     virtualenv_site_packages: yes
#   loop: "{{install_pip|dictsort|map(attribute='1')|map(attribute='packages')|flatten}}"


###################################################################################
- set_fact:
    PIP_BINPROVIDERS:
      pip:
        installer_abspath: "{{BINARIES.pip.abspath}}"
        installer_version: "{{BINARIES.pip.version}}"
        PATH: "{{LIB_DIR_PIP_BIN}}"
        virtualenv: "{{LIB_DIR_PIP}}/venv"
        virtualenv_python: "{{BINARIES.python.abspath}}"
  when: BINPROVIDERS.pip is not defined

- set_fact:
    BINPROVIDERS: "{{ BINPROVIDERS | default({}) | combine(PIP_BINPROVIDERS) }}"
    cacheable: true
  when: BINPROVIDERS.pip is not defined

- debug:
    msg: "{{ {'BINARIES': BINARIES, 'BINPROVIDERS': BINPROVIDERS} }}"
