---
argument_specs:
  main:
    short_description: Main entry point for the npm role

    options:
    
      state:
        type: "str"
        required: false
        default: 'present'
        description:
          - "The desired state: present | latest"

      npm_packages:
        type: "list"
        elements: "dict"
        required: false
        default: []
        description: "A list of dicts with a defined structure and with default a value."
        options:
          key:
            type: "str"
            required: true
            description: "A string name for the dependency"

          packages:
            type: "list"
            elements: "str"
            required: true
            description: "What npm packages to install for the given dependency."
