name: Build Pip package

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    permissions:
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - name: Install uv build dependencies
        run: uv sync --frozen --all-extras --no-install-project --no-install-workspace

      - name: Build package
        run: |
          uv build --all

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: ripgrep build-essential python3-dev python3-setuptools libssl-dev libldap2-dev libsasl2-dev zlib1g-dev libatomic1 gnupg2 curl wget python3-ldap python3-msgpack python3-mutagen python3-regex python3-pycryptodome procps
      #     version: 1.0

      # - name: Install from build
      #   run: uv pip install ./dist/*.whl

      # - name: Add some links to test
      #   run: |
      #     mkdir data && cd data
      #     archivebox init
      #     archivebox add 'https://example.com'
      #     archivebox version
      #     archivebox status


